global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: default-receiver
  routes:
  - match:
      severity: critical
    receiver: email-receiver
  - match:
      notify: telegram
    receiver: telegram-receiver

receivers:

- name: default-receiver

- name: email-receiver
  email_configs:
  - to: 'xxx'
    from: 'xxx'
    require_tls: false
    smarthost: 'smtp.gmail.com:465'
    auth_username: 'xxx'
    auth_password: 'xxx'

- name: telegram-receiver
  telegram_configs:
    - bot_token: "xxx"
      chat_id: -xxx
