scrape_configs:
  - job_name: 'postgres'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets:
        - server1:5432
        - server2:5432
    metrics_path: /probe
    params:
      auth_module: [foo]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ['localhost:9116']

  - job_name: 'grafana_metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
    - targets: ['localhost:3000']  
