version: "3.9"
services:
  postgresql-server:
    container_name: postgres
    image: postgres:15.2
    restart: always
    volumes:
      - ./postgresql_server:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ncuser
      POSTGRES_USER: ncuser
      POSTGRES_DB: ncdb
    ports:
      - "5432:5432"

  nextcloud-server:
    container_name: nextcloud
    image: nextcloud:26.0.1-fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - ./nextcloud_server:/var/www/html
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      POSTGRES_HOST: postgresql-server
      POSTGRES_DB: ncdb
      POSTGRES_USER: ncuser
      POSTGRES_PASSWORD: ncuser
      NEXTCLOUD_ADMIN_PASSWORD: admin
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_TRUSTED_DOMAINS: 192.168.0.19:80 192.168.0.19:443
    depends_on:
      - postgresql-server

  onlyoffice-document-server:
    container_name: onlyoffice-document
    image: onlyoffice/documentserver:7.3.3
    restart: always
    environment:
      - JWT_ENABLED=false
    expose:
      - '80'
      - '443'
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
  
  nginx-server:
    container_name: nginx
    image: nginx:1.24
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nextcloud_server:/var/www/html
      - ./nginx-log:/var/log/nginx