scrape_configs:
  - job_name: node
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'grafana_metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
    - targets: ['localhost:3000']

  - job_name: 'nextcloud-exporter'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
    - targets: ['localhost:8080']
  
remote_write:
- url: https://prometheus-prod-13-prod-us-east-0.grafana.net/api/prom/push
  basic_auth:
    username: ${PROM_REMOTE_WRITE_USERNAME}
    password: ${PROM_REMOTE_WRITE_PASSWORD}