version: '3.9'

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana.ini:/etc/grafana/grafana.ini
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      - default

  postgresql-server:
    container_name: postgres
    image: postgres:15.2
    restart: always
    volumes:
      - ./postgresql_server:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ncuser
      POSTGRES_USER: ncuser
      POSTGRES_DB: ncdb
    ports:
      - 5432:5432

  postgres_exporter:
    image: wrouesnel/postgres_exporter 
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME : "ncdb"
      DATA_SOURCE_USER : "ncuser"
      DATA_SOURCE_PASS : "ncuser"
      TZ: "Europe/Moscow"
    ports:
      - 9116:9116
    restart: unless-stopped
    networks:
      - default


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16