scrape_configs:
  - job_name: node # node exporter
    scrape_interval: 5s
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'grafana_metrics' # grafana metrics
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
    - targets: ['localhost:3000']

  - job_name: 'nextcloud-exporter' # nextcloud exporter
    scrape_interval: 90s
    static_configs:
      - targets: ['localhost:9205']

  - job_name: 'nextcloud-exporter' # nextcloud exporter
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
    - targets: ['localhost:8080']